/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminCardsRouteImport } from './routes/_authenticated/admin.cards'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminStrategiesRouteImport } from './routes/_authenticated/admin.strategies'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin.transactions'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminYieldsRouteImport } from './routes/_authenticated/admin.yields'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardCopilotRouteImport } from './routes/_authenticated/dashboard.copilot'
import { Route as AuthenticatedDashboardGoalsRouteImport } from './routes/_authenticated/dashboard.goals'
import { Route as AuthenticatedDashboardHelpRouteImport } from './routes/_authenticated/dashboard.help'
import { Route as AuthenticatedDashboardMarketsRouteImport } from './routes/_authenticated/dashboard.markets'
import { Route as AuthenticatedDashboardPortfolioRouteImport } from './routes/_authenticated/dashboard.portfolio'
import { Route as AuthenticatedDashboardSendReceiveRouteImport } from './routes/_authenticated/dashboard.send-receive'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardSpendRouteImport } from './routes/_authenticated/dashboard.spend'
import { Route as AuthenticatedDashboardTransactionsRouteImport } from './routes/_authenticated/dashboard.transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCardsRoute = AuthenticatedAdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStrategiesRoute =
  AuthenticatedAdminStrategiesRouteImport.update({
    id: '/strategies',
    path: '/strategies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminYieldsRoute =
  AuthenticatedAdminYieldsRouteImport.update({
    id: '/yields',
    path: '/yields',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCopilotRoute =
  AuthenticatedDashboardCopilotRouteImport.update({
    id: '/copilot',
    path: '/copilot',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGoalsRoute =
  AuthenticatedDashboardGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHelpRoute =
  AuthenticatedDashboardHelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMarketsRoute =
  AuthenticatedDashboardMarketsRouteImport.update({
    id: '/markets',
    path: '/markets',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPortfolioRoute =
  AuthenticatedDashboardPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSendReceiveRoute =
  AuthenticatedDashboardSendReceiveRouteImport.update({
    id: '/send-receive',
    path: '/send-receive',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSpendRoute =
  AuthenticatedDashboardSpendRouteImport.update({
    id: '/spend',
    path: '/spend',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTransactionsRoute =
  AuthenticatedDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/strategies': typeof AuthenticatedAdminStrategiesRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/yields': typeof AuthenticatedAdminYieldsRoute
  '/dashboard/copilot': typeof AuthenticatedDashboardCopilotRoute
  '/dashboard/goals': typeof AuthenticatedDashboardGoalsRoute
  '/dashboard/help': typeof AuthenticatedDashboardHelpRoute
  '/dashboard/markets': typeof AuthenticatedDashboardMarketsRoute
  '/dashboard/portfolio': typeof AuthenticatedDashboardPortfolioRoute
  '/dashboard/send-receive': typeof AuthenticatedDashboardSendReceiveRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/spend': typeof AuthenticatedDashboardSpendRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/strategies': typeof AuthenticatedAdminStrategiesRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/yields': typeof AuthenticatedAdminYieldsRoute
  '/dashboard/copilot': typeof AuthenticatedDashboardCopilotRoute
  '/dashboard/goals': typeof AuthenticatedDashboardGoalsRoute
  '/dashboard/help': typeof AuthenticatedDashboardHelpRoute
  '/dashboard/markets': typeof AuthenticatedDashboardMarketsRoute
  '/dashboard/portfolio': typeof AuthenticatedDashboardPortfolioRoute
  '/dashboard/send-receive': typeof AuthenticatedDashboardSendReceiveRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/spend': typeof AuthenticatedDashboardSpendRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/strategies': typeof AuthenticatedAdminStrategiesRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/yields': typeof AuthenticatedAdminYieldsRoute
  '/_authenticated/dashboard/copilot': typeof AuthenticatedDashboardCopilotRoute
  '/_authenticated/dashboard/goals': typeof AuthenticatedDashboardGoalsRoute
  '/_authenticated/dashboard/help': typeof AuthenticatedDashboardHelpRoute
  '/_authenticated/dashboard/markets': typeof AuthenticatedDashboardMarketsRoute
  '/_authenticated/dashboard/portfolio': typeof AuthenticatedDashboardPortfolioRoute
  '/_authenticated/dashboard/send-receive': typeof AuthenticatedDashboardSendReceiveRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/spend': typeof AuthenticatedDashboardSpendRoute
  '/_authenticated/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cards'
    | '/admin/settings'
    | '/admin/strategies'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/yields'
    | '/dashboard/copilot'
    | '/dashboard/goals'
    | '/dashboard/help'
    | '/dashboard/markets'
    | '/dashboard/portfolio'
    | '/dashboard/send-receive'
    | '/dashboard/settings'
    | '/dashboard/spend'
    | '/dashboard/transactions'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cards'
    | '/admin/settings'
    | '/admin/strategies'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/yields'
    | '/dashboard/copilot'
    | '/dashboard/goals'
    | '/dashboard/help'
    | '/dashboard/markets'
    | '/dashboard/portfolio'
    | '/dashboard/send-receive'
    | '/dashboard/settings'
    | '/dashboard/spend'
    | '/dashboard/transactions'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/cards'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/strategies'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/yields'
    | '/_authenticated/dashboard/copilot'
    | '/_authenticated/dashboard/goals'
    | '/_authenticated/dashboard/help'
    | '/_authenticated/dashboard/markets'
    | '/_authenticated/dashboard/portfolio'
    | '/_authenticated/dashboard/send-receive'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/spend'
    | '/_authenticated/dashboard/transactions'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cards': {
      id: '/_authenticated/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AuthenticatedAdminCardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/strategies': {
      id: '/_authenticated/admin/strategies'
      path: '/strategies'
      fullPath: '/admin/strategies'
      preLoaderRoute: typeof AuthenticatedAdminStrategiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/yields': {
      id: '/_authenticated/admin/yields'
      path: '/yields'
      fullPath: '/admin/yields'
      preLoaderRoute: typeof AuthenticatedAdminYieldsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/copilot': {
      id: '/_authenticated/dashboard/copilot'
      path: '/copilot'
      fullPath: '/dashboard/copilot'
      preLoaderRoute: typeof AuthenticatedDashboardCopilotRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/goals': {
      id: '/_authenticated/dashboard/goals'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof AuthenticatedDashboardGoalsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/help': {
      id: '/_authenticated/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof AuthenticatedDashboardHelpRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/markets': {
      id: '/_authenticated/dashboard/markets'
      path: '/markets'
      fullPath: '/dashboard/markets'
      preLoaderRoute: typeof AuthenticatedDashboardMarketsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/portfolio': {
      id: '/_authenticated/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof AuthenticatedDashboardPortfolioRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/send-receive': {
      id: '/_authenticated/dashboard/send-receive'
      path: '/send-receive'
      fullPath: '/dashboard/send-receive'
      preLoaderRoute: typeof AuthenticatedDashboardSendReceiveRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/spend': {
      id: '/_authenticated/dashboard/spend'
      path: '/spend'
      fullPath: '/dashboard/spend'
      preLoaderRoute: typeof AuthenticatedDashboardSpendRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/transactions': {
      id: '/_authenticated/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCardsRoute: typeof AuthenticatedAdminCardsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStrategiesRoute: typeof AuthenticatedAdminStrategiesRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminYieldsRoute: typeof AuthenticatedAdminYieldsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCardsRoute: AuthenticatedAdminCardsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStrategiesRoute: AuthenticatedAdminStrategiesRoute,
  AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminYieldsRoute: AuthenticatedAdminYieldsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCopilotRoute: typeof AuthenticatedDashboardCopilotRoute
  AuthenticatedDashboardGoalsRoute: typeof AuthenticatedDashboardGoalsRoute
  AuthenticatedDashboardHelpRoute: typeof AuthenticatedDashboardHelpRoute
  AuthenticatedDashboardMarketsRoute: typeof AuthenticatedDashboardMarketsRoute
  AuthenticatedDashboardPortfolioRoute: typeof AuthenticatedDashboardPortfolioRoute
  AuthenticatedDashboardSendReceiveRoute: typeof AuthenticatedDashboardSendReceiveRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSpendRoute: typeof AuthenticatedDashboardSpendRoute
  AuthenticatedDashboardTransactionsRoute: typeof AuthenticatedDashboardTransactionsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCopilotRoute: AuthenticatedDashboardCopilotRoute,
    AuthenticatedDashboardGoalsRoute: AuthenticatedDashboardGoalsRoute,
    AuthenticatedDashboardHelpRoute: AuthenticatedDashboardHelpRoute,
    AuthenticatedDashboardMarketsRoute: AuthenticatedDashboardMarketsRoute,
    AuthenticatedDashboardPortfolioRoute: AuthenticatedDashboardPortfolioRoute,
    AuthenticatedDashboardSendReceiveRoute:
      AuthenticatedDashboardSendReceiveRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSpendRoute: AuthenticatedDashboardSpendRoute,
    AuthenticatedDashboardTransactionsRoute:
      AuthenticatedDashboardTransactionsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
