/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardCopilotRouteImport } from './routes/dashboard.copilot'
import { Route as DashboardGoalsRouteImport } from './routes/dashboard.goals'
import { Route as DashboardMarketsRouteImport } from './routes/dashboard.markets'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardSendReceiveRouteImport } from './routes/dashboard.send-receive'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSpendRouteImport } from './routes/dashboard.spend'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCopilotRoute = DashboardCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGoalsRoute = DashboardGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketsRoute = DashboardMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSendReceiveRoute = DashboardSendReceiveRouteImport.update({
  id: '/send-receive',
  path: '/send-receive',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSpendRoute = DashboardSpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/copilot': typeof DashboardCopilotRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/markets': typeof DashboardMarketsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/send-receive': typeof DashboardSendReceiveRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/spend': typeof DashboardSpendRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard/copilot': typeof DashboardCopilotRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/markets': typeof DashboardMarketsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/send-receive': typeof DashboardSendReceiveRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/spend': typeof DashboardSpendRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/copilot': typeof DashboardCopilotRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/markets': typeof DashboardMarketsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/send-receive': typeof DashboardSendReceiveRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/spend': typeof DashboardSpendRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/dashboard/copilot'
    | '/dashboard/goals'
    | '/dashboard/markets'
    | '/dashboard/portfolio'
    | '/dashboard/send-receive'
    | '/dashboard/settings'
    | '/dashboard/spend'
    | '/dashboard/transactions'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard/copilot'
    | '/dashboard/goals'
    | '/dashboard/markets'
    | '/dashboard/portfolio'
    | '/dashboard/send-receive'
    | '/dashboard/settings'
    | '/dashboard/spend'
    | '/dashboard/transactions'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/dashboard/copilot'
    | '/dashboard/goals'
    | '/dashboard/markets'
    | '/dashboard/portfolio'
    | '/dashboard/send-receive'
    | '/dashboard/settings'
    | '/dashboard/spend'
    | '/dashboard/transactions'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/copilot': {
      id: '/dashboard/copilot'
      path: '/copilot'
      fullPath: '/dashboard/copilot'
      preLoaderRoute: typeof DashboardCopilotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/goals': {
      id: '/dashboard/goals'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof DashboardGoalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/markets': {
      id: '/dashboard/markets'
      path: '/markets'
      fullPath: '/dashboard/markets'
      preLoaderRoute: typeof DashboardMarketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/send-receive': {
      id: '/dashboard/send-receive'
      path: '/send-receive'
      fullPath: '/dashboard/send-receive'
      preLoaderRoute: typeof DashboardSendReceiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/spend': {
      id: '/dashboard/spend'
      path: '/spend'
      fullPath: '/dashboard/spend'
      preLoaderRoute: typeof DashboardSpendRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCopilotRoute: typeof DashboardCopilotRoute
  DashboardGoalsRoute: typeof DashboardGoalsRoute
  DashboardMarketsRoute: typeof DashboardMarketsRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardSendReceiveRoute: typeof DashboardSendReceiveRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSpendRoute: typeof DashboardSpendRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCopilotRoute: DashboardCopilotRoute,
  DashboardGoalsRoute: DashboardGoalsRoute,
  DashboardMarketsRoute: DashboardMarketsRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardSendReceiveRoute: DashboardSendReceiveRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSpendRoute: DashboardSpendRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
